### PR TITLE
Fix broken documentation link

### PR DESCRIPTION
**Pull request by kalenwatermeyer**
**Readme.md**
The link to Seleno documentation is broken. 

I've updated the URL to point to: http://seleno.teststack.net/docs/introduction-to-seleno

### CODE REVIEW

**Comment by robdmoore** [comment]
Can you please make it http://seleno.teststack.net instead?

**Comment by kalenwatermeyer** [comment]
Hi @robdmoore - I've updated the documentation url as requested.

(I'm a noob with the online GitHub pull request workflow - sorry if I've messed it up!)

**Comment by robdmoore** [comment]
Hi @kalenwatermeyer - thanks for the PR :)

It looks like you created pull requests to your own master branch and then created a pull request from your master branch to Seleno - this meant that rather than one commit there was 4 commits. Because of that, in this case I've made the change myself.

In the future you can create a pull request from a non-master branch directly to Seleno (or any other repository) - that will come through a lot cleaner :) There is some more information here FYI: https://help.github.com/articles/using-pull-requests/

Thanks again :)

**Comment by kalenwatermeyer** [comment]
Thanks for the tip Rob - I'll get my pull requests right next time!

Cheers
Kalen

**Pull request closed without merging**
