### PR TITLE
Context file camera

### PR DESCRIPTION
**Pull request by dennisroche**
A new file camera that bakes additional/contextual information into the image. I found this additional information useful when debugging why a test failed and where in the callstack the image was generated.

To make this information even more useful, I added `Exception` param to the `ICamera.TakeScreenshot` interface. It defaults to `null`.

**Example**

elementfinder_2014-11-03_15-00-59 png_130595004593300652

**Usage**

``` c#
_host = new SelenoHost();
_host.Run(x => x
    .UsingCamera(new ContextFileCamera(CameraFolderPath, typeof(TestAttribute)))
    .WithWebServer(new InternetWebServer("http://www.google.com/"))
    .WithMinimumWaitTimeoutOf(TimeSpan.FromMilliseconds(100))
);
```

I'm not too happy with the having to pass down the attribute type that decorate the test, i.e. `typeof(TestAttribute)` for NUnit. However I couldn't think of a generic way to handle this.

### CODE REVIEW

**Comment by robdmoore** [comment]
Hey @dennisroche what's the status on changing that test attribute? Do you think we should merge in the meantime regardless and do that in a separate PR? I also wonder if we can do an acceptance test of this with an image comparison - main tricky thing would be the date (maybe we can figure a way to fix it for the test?).

**Comment by dennisroche** [comment]
@robdmoore I haven't made any progress on it. I did spike an idea, however it got left on the wayside months ago. I will have make time on Thursday night to revisit this and get it to merge ready state with test attribute removed and an acceptance test. 

For the acceptance test, I was going to use/create a page in the current test project and then fix the time using the `SystemTime` package that @mwhelan recently introduced to the solution.

**Comment by dennisroche** [comment]
Rebased with master. I've made the suggested changes to detecting the testing framework and added an acceptance test for the `ContextFileCamera` that compares the image.

**Comment by robdmoore** [comment]
You are going to need to set the browser window size to a certain size otherwise it will vary based on the computer it's running on. For instance, that test failed on the build server.

Don't make it more than 800x600 as a lowest common denominator.

**Comment by dennisroche** [comment]
Thanks @robdmoore. I thought that would happen as I had the test fail locally once with a image of different dimensions.

**Comment by robdmoore** [comment]
FYI There are a bunch of broken acceptance tests on your latest commit in the build server.

**Comment by dennisroche** [comment]
Closing this PR as it over 3 years old.

**Comment by robdmoore** [comment]
This is still incredibly useful. The main issue is that Seleno hasn't received any love for a long time. I'd prefer this is left open to it's clear if Seleno is ressurected at any point.

**Comment by dennisroche** [comment]
Fair enough; it would be good to see Seleno live again.

**Comment by mwhelan** [comment]
Hey Dennis

I'm the original creator of Seleno and I would love to see it live again too. When I made it I was doing a lot of Selenium WebDriver work but it's been quite awhile since I've used Selenium and it's been hard to keep up with the project. It would be good to start off with supporting the latest version of WebDriver and investigate what might be involved with porting it to .Net Core. I think that would be possible with .Net Core 2.0.

Thanks

**Comment by dennisroche** [comment]
@mwhelan perhaps that is why it has dropped to the side as not many people are using Selenium UI testing, especially on ASP.NET MVC apps (it has been years since I last created one). 

> It would be good to start off with supporting the latest version of WebDriver and investigate what might be involved with porting it to .Net Core. I think that would be possible with .Net Core 2.0.

Porting to .NET Core 2 looks possible (see attached report). Probably would have some serious breaking changes for existing users because of ASPNET.Core 

[Seleno - I Can Has .NET Core.pdf](https://github.com/TestStack/TestStack.Seleno/files/1743250/Seleno.-.I.Can.Has.NET.Core.pdf)

**Pull request closed without merging**
